### ISSUE TITLE
Specification of Generic-based instance of FromConfig

### ISSUE THREAD

**Issue by debug-ito** [ludat/conferer#113]
Is there any specification or documents on how the `Generic`-based instance of `FromConfig` is implemented? Specifically, what is the mapping between the record field names and `Key`s?

For example, in the [Multiple configs and generics tutorial](https://conferer.ludat.io/docs/multiple-tutorial), `FromConfig` instance for `AppConfig` is given by the library based on the `Generic`.

```haskell
data AppConfig = AppConfig
  { appConfigWarp :: Warp.Settings
  , appConfigRedis :: Hedis.ConnectionInfo
  , appConfigSecret :: Text
  } deriving (Show, Generic)

instance FromConfig AppConfig
```

How does that `FromConfig` instance map the field names to `Key`s? Does it automatically remove `appConfig` prefix? If so, can I customize that mapping rule?

In addition, the later part of the tutorial says that `server.port` key maps to the warp's listening port parameter. However, I cannot understand where the `server` prefix comes.

**Comment by ludat** [comment]
On the documentation of Generic instances: sadly it's not documented on the site right now, at least not directly, it's mostly on that page that you mention. You can look at the tests which I think are fairly easy to read but I agree that we should have that documented in the site.

On the `server.port` thing, yes! that's a typo, it should be `warp.port`.

The logic for the field to key transformation is stripping the name of the constructor from the field. so if the field is named `MyRecordSomethig` and the field is `myRecordSomethigField` will result in the key `field`.

NOTES:
* if the constructor is not a prefix of the field then we take it literally (the field)
* we first lowercase the first character of the constructor, do the prefix and then lowercase the first char of the left field

**Comment by debug-ito** [comment]
Thanks for clarification!
