### ISSUE TITLE
version bounds on packages published to hackage are outdated

### ISSUE THREAD

**Issue by stuebinm** [ludat/conferer#115]
although https://github.com/ludat/conferer/pull/110 updated the version bounds for the `text` and `aeson` packages, these seem to only partially be packaged on hackage: e.g. for the `conferer` package the [cabal file of the latest revision](https://hackage.haskell.org/package/conferer-1.1.0.0/revision/3.cabal) has `text < 2.1` for the library, but not the test suite, where it still has `text < 1.3`, so building the tests still fails. The same is true for the other `conferer-*` packages.

**Comment by ludat** [comment]
Hi, thanks for the report

I've updated the revisions of some of the packages and now I think they are ok, can you check?

**Comment by stuebinm** [comment]
yes, they build fine now, thanks!
