### ISSUE TITLE
Samples in doc are lacking imports.

### ISSUE THREAD

**Issue by yaitskov** [ludat/conferer#57]
e.g. I cannot locate defaultConfig function. Where it comes from?

**Comment by ludat** [comment]
Sorry the `defaultConfig` function was renamed to `mkConfig` in a recent release.

Where are you reading the docs from? (I imagine I forgot to update some docs somewhere)

Try using the latest version of conferer (1.1.0.0) and the docs are available on https://conferer.ludat.io/

**Comment by ludat** [comment]
Is this already solved @yaitskov? I'll close it tomorrow if so
