### ISSUE TITLE
Cannot build with nix 

### ISSUE THREAD

**Issue by yaitskov** [ludat/conferer#62]
Hi.

I modified library and wanted build with nix just from git, nix fails.
It looks like it cannot handle inclusion of package.common.yaml with macros. I face such trick first time. What is the technology used?

```
*** hpack error: "/nix/store/pa122xh2pjk86w228ld7v7cbcl9k3s5v-source
/package.yaml: 
Yaml file not found: /home/dan/demo/haskell/conferer/conferer/utils/package.common.yaml". 
Exiting.

```

```
  myhaskellPackages = haskell.packages.ghc8104.extend (self: super: {

    conferer = self.callCabal2nix "conferer" ../../haskell/conferer/conferer
/packages/conferer {};

```

**Comment by ludat** [comment]
Hmm, I don't use nix but I think you could simply ignore the `package.yml` (so avoid using `hpack` at all) since the `conferer.cabal` is commited and we always keep up to date.

**Comment by yaitskov** [comment]
I am working with nix for a few weeks. 
I use callCabal2nix command it looks into package.yaml (hpack) :)

**Comment by ludat** [comment]
So this is something that's part of the yaml spec, it's called anchors, I think the problem probably is that when you build the package you are only providing nix with the `packages/conferer` directory and that's not enough. But you can try avoiding hpack completely, maybe there is a flag you can pass to `callCabal2nix` or maybe you could delete the `package.yaml` before calling it.

**Comment by yaitskov** [comment]
Thanks for explanations. I forwarded [issue to hpack tracker](https://github.com/sol/hpack/issues/441).
